### ISSUE TITLE
control message length

### ISSUE THREAD

**Issue by aleixmorgadas** [aleixmorgadas/nem2-nonfungible-asset#1]
The current implementation doesn't control the message length, it might cause a `catapult-exception` when it's larger than `1024` characters as current catapult config limit of message size.

In case for `asset` definition message, it has to be limitated in the constructor to check if's not larger than 1024 chars, since it's required that the definition fits in one message.

For `metadata`, we have two cases.

1. the Key-Value is larger than 1024 chars, it' has to throw an exception.
2. the concatenation of Key-Value metadata is larger than 1024 chars, then the metadata has to be chunked in multiple messages. This case has to be handled when we read from network too.

@CrackTheCode016 , do you need more details?

**Comment by aleixmorgadas** [comment]
example for case 1:

[`key_of_enough_length`, `value_of_enough_length`]. that key.length + value.length > 1024, then throw the error. Take into account that the message has a prefix (`metadata(1):`), the values are separated by commas `,` and each metadata is separated by dots `.`

The second case shouldn't throw an error, instead, it should divide the metadata in multiple messages in order to fit in the message size and keep the information.

**Comment by CrackTheCode016** [comment]
I just realized the prefix, otherwise I believe the rest of case 1 is good.  Thank you for pointing that out.  Multiple messages = multiple transactions correct? And when fetching those multiple transactions we get the messages and string them together?

**Comment by aleixmorgadas** [comment]
> Multiple messages = multiple transactions correct?

yes

> And when fetching those multiple transactions we get the messages and string them together?

We will see.

Let's start with the class `Asset` to control the cases I shared, later, we will find out how to read from the network

**Comment by CrackTheCode016** [comment]
I am still a little confused with why we need case 1 and case 2.  Case 1 we simply check the WHOLE key-value character length and throw an error on > 1024 chars. Why do we need to throw an error?  Why can't we just check if more than 1024 and then split it into multiple messages, and just have one case where we do this?

**Comment by aleixmorgadas** [comment]
example of metadata:

one metadata→`metadata(1):key,value`
two metadata → `metadata(1):key1,value1.key2,value2`

to split the metadata into different, I concat them via a dot. so, we can split the different metadata pairs in different messages. BUT, key and value must be in the same message since they need to be together.

**Comment by CrackTheCode016** [comment]
Very clear thank you

**Comment by CrackTheCode016** [comment]
I have fixed the issues and now am working on tests
