### ISSUE TITLE
create asset without namespace

### ISSUE THREAD

**Issue by thomas-tri-tran** [aleixmorgadas/nem2-nonfungible-asset#15]
Can we create the asset without the namespace?

**Comment by aleixmorgadas** [comment]
Yes, you don't need a namespace to create an asset.

https://github.com/aleixmorgadas/nem2-nonfungible-asset/blob/master/src/Asset.ts#L32

I ask for a source, which it's just a logical representation of _an asset belong to "something"_. It's good that the account that issue an asset owns the namespace for being trust in the network but it's not necessary.

Why did you think that it was necessary at first place?

**Comment by thomas-tri-tran** [comment]
There is no document and I thought we need to have the namespace and create an asset under the namespace like the mosaic.
